services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app 
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    command: sh -c "npm run dev"
    platform: linux/x86_64
    ports:
      - 3000:3000
  db:
    image: "postgres:latest"
    platform: linux/x86_64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
  node_modules:
